DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS quizes CASCADE;

CREATE TABLE quizzes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  short_url VARCHAR(6) REFERENCES questions(id) ON DELETE CASCADE NOT NULL,
  question1 INTEGER REFERENCES questions(id) ON DELETE CASCADE,
  question2 INTEGER REFERENCES questions(id) ON DELETE CASCADE,
  question3 INTEGER REFERENCES questions(id) ON DELETE CASCADE,
  question4 INTEGER REFERENCES questions(id) ON DELETE CASCADE
);

CREATE TABLE questions (
  id SERIAL PRIMARY KEY NOT NULL,
  quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE NOT NULL,
  correctAnswer INTEGER NOT NULL,
  answer1 VARCHAR(255) NOT NULL,
  answer2 VARCHAR(255) NOT NULL,
  answer3 VARCHAR(255),
  answer4 VARCHAR(255)
);
