DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS quizes CASCADE;

CREATE TABLE questions (
  id SERIAL PRIMARY KEY NOT NULL,
  correctAnswer INTEGER NOT NULL,
  answer1 VARCHAR(255) NOT NULL,
  answer2 VARCHAR(255) NOT NULL,
  answer3 VARCHAR(255),
  answer4 VARCHAR(255),
);

CREATE TABLE quizes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) DELETE ON CASCADE NOT NULL,
  short_url VARCHAR(6) REFERENCES questions(id) DELETE ON CASCADE NOT NULL
  question1 INTEGER REFERENCES questions(id) DELETE ON CASCADE NOT NULL,
  question2 INTEGER REFERENCES questions(id) DELETE ON CASCADE NOT NULL,
  question3 INTEGER REFERENCES questions(id) DELETE ON CASCADE NOT NULL,
  question4 INTEGER REFERENCES questions(id) DELETE ON CASCADE NOT NULL,
);
